apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    build.appstudio.openshift.io/application: glbc
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: component
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: component
  namespace: jmadigan
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_Kuadrant_kcp-glbc
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/Kuadrant/kcp-glbc.git
